places_to_order_from:
  -
    name: Noodle w pudle
    url: http://www.noodlewpudle.pl
    phones:
      - 71 725 42 42
  -
    name: Pizza station
    url: http://www.pizzastation.pl
    phones:
      - 71 790 33 66
# tip: use http://www.itouchmap.com/latlong.html to quickly find the coordinates of a restaurant

places_to_go_to:
  -
    name: FC naleśniki
    url: https://www.facebook.com/pages/FC-Naleśniki
    lat: 51.110967
    lng: 17.033732
  -
    name: Bar miś
    lat: 51.112478
    lng: 17.034170
  -
    name: Bernard
    url: http://www.bernard.wroclaw.pl
    lat: 51.109986
    lng: 17.033396